### PR TITLE
Re-implemented 'dummy' adapter

### LINKED ISSUE #243: sqlform.factory issue
It seems to me that sqlform factory is broken. Git bisect traced it down to commit @03dc3a8d4cddf3c1fd92cdab62d923d64f777776

```
Traceback (most recent call last):
  File "/home/marin/web2py/gluon/restricted.py", line 227, in restricted
    exec ccode in environment
  File "/home/marin/web2py/applications/move/controllers/user.py", line 142, in <module>
  File "/home/marin/web2py/gluon/globals.py", line 412, in <lambda>
    self._caller = lambda f: f()
  File "/home/marin/web2py/applications/move/controllers/user.py", line 98, in login
    form = SQLFORM.factory(Field('email', 'string'), Field('password', 'string')).process(keepvalues=True)
  File "/home/marin/web2py/gluon/html.py", line 2301, in process
    self.validate(**kwargs)
  File "/home/marin/web2py/gluon/html.py", line 2238, in validate
    if self.accepts(**kwargs):
  File "/home/marin/web2py/gluon/sqlhtml.py", line 1688, in accepts
    self.vars.id = self.table.insert(**fields)
  File "/home/marin/web2py/gluon/packages/dal/pydal/objects.py", line 706, in insert
    ret = self._db._adapter.insert(self, self._listify(fields))
  File "/home/marin/web2py/gluon/packages/dal/pydal/adapters/base.py", line 737, in insert
    raise e
ValueError: INSERT INTO no_table(password,email) VALUES ('password','test.marin@entropia.hr');
```

### PR DESCRIPTION
**Pull request by gi0baro**
Closes #243 re-implementing the old `Dummy` adapter removed by #226

### CODE REVIEW

**Comment by mdipierro** [comment]
This does no pass some tests. Why do you want a FakeCursor instead of a DummyAdapter. What is the purpose of parsing all the query tree and generate queries if they are never passed to a database engine?

**Comment by gi0baro** [comment]
@mdipierro `FakeCursor` is implemented to be compliant with the changes added by #226 
`NullAdapter` is exactly the same of the old `DummyAdapter`, just using the `NullCursor`. 
Even with your old `DummyAdapter` (prior to #226) queries were generated.

BTW, errors are only on google adapters, will review the code in the next hours and will push another commit to fix it.
Then this PR will be merge-able.

**Comment by mdipierro** [comment]
Perfect. Thanks for the explanation.

**Comment by gi0baro** [comment]
@mdipierro Ready for merge

**Pull request merged**
