### PR TITLE
added BasicStorage

### PR DESCRIPTION
**Pull request by ilvalle**
BasicStroage has the performance of web2py FastStorage without the memory leak.
DAL, Row & Table inherit from BasicStorage

Fix https://github.com/web2py/web2py/issues/932

### CODE REVIEW

**Comment by gi0baro** [comment]
Why *BasicStorage2* and not *BasicStorage*? Probably I would named it *DALobject*..

**Comment by ilvalle** [comment]
BasicStorage is more appropriate.
In my view, by changing only a couple of methods it can easily became the
super class of web2py Storage, this is the reason of naming it as
BasicStorage. The difference is that, BasicStorage raise an
attribute/keyError when an attribute/item is not available, Storage return
None. Anyway, this is not fully related to this PR

 Paolo

2015-04-27 8:13 GMT+02:00 Giovanni Barillari <notifications@github.com>:

**Comment by gi0baro** [comment]
Ok, but you named the class *BasicStorage2*..

**Comment by ilvalle** [comment]
I can't rename it right now. Beside the name, if you accept the patch,
merge it. I'll rename the class later today or tomorrow.

 Paolo

2015-04-27 9:01 GMT+02:00 Giovanni Barillari <notifications@github.com>:

**Comment by gi0baro** [comment]
Ok, I'm gonna accept this, and rename the class in py3 branch with python3 fixtures

**Pull request merged**
