### PR TITLE
version file

### PR DESCRIPTION
**Pull request by ilvalle**

### CODE REVIEW

**Comment by gi0baro** [comment]
Why this?

**Comment by ilvalle** [comment]
Can be used in any project using pydal

**Comment by gi0baro** [comment]
Ok, but the build is broken and maybe is better to hardcode the version inside the package

**Comment by niphlod** [comment]
dunno about the requirement of having an external version file, but the read_file implementation is silly since 2.4 was never in scope (actually, I seem to recall that 2.5 was dropped too). There's the much more standard - and elegant - 
    with open('foo/bar', 'r') as f:
           content = f.read()
works in jython and pypy too.

**Comment by mdipierro** [comment]
ok. let's fix the implementation as suggested by niphlod. I do not object to have a VERSION file. It is cleaner.

**Comment by mdipierro** [comment]
What do we do about this?

**Comment by ilvalle** [comment]
Beside the implementation, is it worth to have such version file?

**Comment by mdipierro** [comment]
I think there is value in knowing the version of pydal programmatically.

**Comment by mdipierro** [comment]
Any news on this? I will close this and wait for a new PR.

**Pull request closed without merging**
