### PR TITLE
Update mongo.py

### PR DESCRIPTION
**Pull request by ftcmnc**
Correction for invalid list:reference representer
Now accepts array of foreign keys

### CODE REVIEW

**Comment by gi0baro** [comment]
@ftcmnc can't see the point of this change. `Representer._represent_list` already parse the lists.

**Comment by ftcmnc** [comment]
@gi0baro I believe this was an issue while using web2py 2.14.6 , it seams to work correctly using pydal 17.07 in web2py 2.15.2

**Comment by ftcmnc** [comment]
Hi @gi0baro after all the problem still persists in pydal 17.07 using web2py 2.15.2
This happens when you have a list of ObjectIds.. if you try to update that list using a form, it passes something like this: `"industries": [ObjectId("578b619a2ba3d3729a442c82")]` to something like this `"industries": [ [ObjectId("578b619a2ba3d3729a442c82")] ]`

**Comment by mdipierro** [comment]
Can you please comment about my comment?

**Comment by gi0baro** [comment]
@ftcmnc @mdipierro seems a web2py problem, not pydal related.

**Comment by mdipierro** [comment]
Maybe. I still do not know what does this happen? We need some come to reproduce the issue. For now the proposed solution does not look the right one.

**Pull request merged**
