### PR TITLE
Initial change to remove ESCAPE from teradata syntax

### PR DESCRIPTION
**Pull request by willimoa**
Fix to Issue 340.

### CODE REVIEW

**Comment by mdipierro** [comment]
This fails the travis tests. Make sure it passes else it will not be accepted.

**Comment by niphlod** [comment]
until https://github.com/web2py/pydal/pull/332 is done, pretty much everything will fail if based on the current master.

**Comment by willimoa** [comment]
OK, sorry.  I may have also submitted my Pull Request incorrectly  (I'll work on an addition to the doco).   Haven't come across Travis tests before, I'll do some reading......

**Comment by willimoa** [comment]
Just read niphlod's post.  Yes, sounds like #332 is a milestone.   I've got some catching up to do.

**Comment by mdipierro** [comment]
Hello willimoa, any chance you will be able to re-submit your pull request for the new dal?

**Comment by willimoa** [comment]
Absolutely, I was waiting for the upgrade.  In a day or two.

Andrew W

**Comment by willimoa** [comment]
I have submitted a pull request but it fails on coverage test.   What do I
need to do?  Add some unit tests?

I haven't contributed for a while and the process, with travis and coverage
is a bit different.

Regards
Andrew Willimott

P.s. I posted to the group re: _lastsql as it is commented out, should I
raise an issue?

**Pull request closed without merging**
