### PR TITLE
Unittest/smart query

### PR DESCRIPTION
**Pull request by BuhtigithuB**
Append "@unittest.skipIf(NOSQL, "Skip nosql")"

### CODE REVIEW

**Comment by BuhtigithuB** [comment]
I think I will have to merge the commit... Another Git skill improvement... If continuous integration failed I will do it...

**Comment by BuhtigithuB** [comment]
appveyor failed with py3.3 and 3.4, but it seems because of lack of MSSQL instance available??

**Comment by ilvalle** [comment]
You can squash the commits into one using git rebase

**Comment by BuhtigithuB** [comment]
yes I did it in my local repo after copied it just in case...

**Comment by BuhtigithuB** [comment]
I close the PR and push the squash branch and PR again... though it seems to have an issue with appveyor and MSSQL Simone seems to work on it...

**Pull request closed without merging**
