### PR TITLE
test and fix as_json when web2py serializer is not available, closes web2py/pydal#112

### PR DESCRIPTION
**Pull request by ilvalle**
I'd consider to backport https://github.com/web2py/web2py/blob/master/gluon/serializers.py (or part of it) in pydal.

### CODE REVIEW

**Comment by gi0baro** [comment]
I'd like to discuss this a bit before a merge, since as you reported we should decide if and how to back port part of the serialization we have in web2py.

**Comment by mdipierro** [comment]
Oops. I merged too soon. Let's discuss and then revert if needed. What do you recommend?

**Comment by ilvalle** [comment]
The alternative is to backport custom_json(), json(), load_json() from web2py

**Comment by ilvalle** [comment]
The alternative is to backport custom_json(), json(), load_json() from web2py

**Pull request merged**
