### PR TITLE
requested by appveyor support

### PR DESCRIPTION
**Pull request by niphlod**
list available MSSQL driver DLL

### CODE REVIEW

**Comment by niphlod** [comment]
@gi0baro : can you wrap your head around it ? see https://github.com/appveyor/ci/issues/268#issuecomment-101778422

**Comment by gi0baro** [comment]
@niphlod Windows is definitely not my "zone", but if it's not tox dependent, I will try to figure out what's happening

**Comment by gi0baro** [comment]
@niphlod py27 is passing, I think was tox related. Will merge this if everything will pass ^^

**Comment by niphlod** [comment]
pinpointed to tox >= 2.. 
Definitely.
``(new) introduce environment variable isolation: tox now only passes the PATH and PIP_INDEX_URL variable from the tox invocation environment to the test environment and on Windows also SYSTEMROOT, PATHEXT, TEMP and TMP whereas on unix additionally TMPDIR is passed. If you need to pass through further environment variables you can use the new passenv setting, a space-separated list of environment variable names. Each name can make use of fnmatch-style glob patterns. All environment variables which exist in the tox-invocation environment will be copied to the test environment.``

seems that both pyodbc and pypyodbc are relying on `WINDIR` to be defined. For all intents and purposes `passenv = WINDIR` added to tox.ini fixes the issue with tox >= 2, but I'm not entirely sure it's safe to do on Linux. For the time being please merge this in. Tomorrow I'm going to push a big piece fixing unicode in MSSQL.

**Pull request merged**
