### PR TITLE
uncomment and fix the typos in tests

### PR DESCRIPTION
**Pull request by BuhtigithuB**
I had mixed up "id" and "integer_field" in string query and query... I also add a test that demonstrate that issue #161 is a false positive and can be closed

### CODE REVIEW

**Comment by BuhtigithuB** [comment]
Don't understand why it failed, it pass locally... :(

**Comment by ilvalle** [comment]
As mentioned in https://github.com/web2py/pydal/issues/161#issuecomment-98799569, the build failed due to the list order. Consider a different test for the IN operator. 
Mind that in https://github.com/web2py/pydal/pull/176 I renamed the file name

**Comment by gi0baro** [comment]
@BuhtigithuB I've merged #176 since it was a good point. Can you rebase this PR from the new code and update the tests for the IN operator as @ilvalle suggested?

**Comment by BuhtigithuB** [comment]
Sure!

Richard

On Mon, May 4, 2015 at 7:00 PM, Giovanni Barillari <notifications@github.com

**Comment by BuhtigithuB** [comment]
About file rename, I appreciate having some guidance, because normally we
name file "test_something", but it is clearly not the case in pydal
project...

**Comment by mdipierro** [comment]
Cannot merge. Does not pass tests. Can you comment about that?

**Comment by BuhtigithuB** [comment]
who should answer... I think it had been included since that time... Is it
the case or not?

I had issue with the PR, that I think Paollo had fixed... So these tests
should had been included if not by my PR.

Richard

**Comment by mdipierro** [comment]
Closing this not because of merit but because this file no longer exist and this PR does not apply

**Pull request closed without merging**
