### PR TITLE
Added version to init

### PR DESCRIPTION
**Pull request by gi0baro**
Alternative to #276

### CODE REVIEW

**Comment by gi0baro** [comment]
Note: the build is not passing only on gae because we had to upgrade the api version for tests

**Comment by ilvalle** [comment]
Should I close the original PR (https://github.com/web2py/pydal/pull/276) ?

**Comment by gi0baro** [comment]
Dunno, I was waiting for feedbacks about the different approach.

**Comment by ilvalle** [comment]
I think that a VERSION file is more cleaner to those people that browser the project.
For applications using pydal having the version in a python file (as in __init__.py) is easier to handle, although a get_version method that reads VERSION can be provide.

**Comment by gi0baro** [comment]
@ilvalle I think that people that browse the project can use git tags to view a specific version, and locally they downloaded a specific version, or the master with git (so they can use tags again). I think this is just the simplest solution for everybody.

**Comment by stephenrauch** [comment]
I also find a VERSION file much cleaner, and would suggest a get_version() that reads the file.

**Comment by ilvalle** [comment]
@gi0baro you are right if people have downloaded the code using git, otherwise you don't have access to git tags.
Given that, I'd update https://github.com/web2py/pydal/pull/276 to provide a get_version() method using the approach proposed by @niphlod in https://github.com/web2py/pydal/pull/276#issuecomment-132325446

**Comment by gi0baro** [comment]
@ilvalle as the developers prefer. 
With my PR `__version__` is accessible inside the pydal package (`pydal.__version__`), and I kept clean the python package (without adding files != .py in the package).
I don't like adding a VERSION file inside the package, and putting it outside the package is just the same of looking at *setup.py* or the changelog (IMHO).

**Comment by mdipierro** [comment]
I am not merging code that does not pass travis tests. Feel free to discuss on dev group.

**Comment by gi0baro** [comment]
@mdipierro this is failing just because is based on the old GAE version, I can rebase with the latest one.

**Pull request merged**
