### PR TITLE
Fix unicode for postgres adapter

### PR DESCRIPTION
**Pull request by ilvalle**
- added a basic 'unicode' test, not sure if it works on all mssql adapters.

### CODE REVIEW

**Comment by gi0baro** [comment]
Seems that is causing errors on mssql + python3.. maybe @niphlod can help on this?

**Comment by niphlod** [comment]
it'll be hardly solvable. In the end, unicode handling with py2 and "without n adapter" was a de-facto "let the magic happen" at the adapter level. I'll see if it's fixable but for all matter and purposes if it works on "with the n adapter" it's thumbs up.

**Comment by gi0baro** [comment]
@mdipierro what about MSSQL?

**Comment by mdipierro** [comment]
I do not know. I followed niphlod's advice. The number of users mssql+py3 is small for us to worry at this point.

**Comment by gi0baro** [comment]
@mdipierro at least we should skip these new tests on MSSQL to avoid broken status on builds.

**Comment by mdipierro** [comment]
I agree. Can you remove them?

**Comment by gi0baro** [comment]
I will do it later today

**Pull request merged**
