### PR TITLE
fix 306 parse_datetime() misrepresentation of millisecond part

### PR DESCRIPTION
**Pull request by kmcheung12**

### CODE REVIEW

**Comment by stephenrauch** [comment]
Good catch on the length of the fractional seconds.  However, I believe the fix proposed fails if more than 6 digits are given.  I would suggest instead something like:

``` python
if ms and ms[0] == '.':
    ms = int(float('0' + ms) * 1000000)
else:
    ms = 0
```

**Comment by kmcheung12** [comment]
@stephenrauch You are right! I have made the corresponding commit

**Comment by stephenrauch** [comment]
@kmcheung12 

This build looks like it failed because of the addition of:

```python
from .base import *
```

in ```tests/__init__.py```.

I am not sure why you needed to do this.  But, I have just committed a change (https://github.com/web2py/pydal/pull/309) which allows this line to work, by fixing these test cases for Mongo, and by disabling the tests for the other NOSQL databases for which these test cases were failing.

**Comment by kmcheung12** [comment]
@stephenrauch import by mistake..

**Comment by gi0baro** [comment]
@kmcheung12 Please, add a commit to this PR to undo changes on the `tests/__init__.py`

**Comment by kmcheung12** [comment]
I have undone the changes on `tests/__init__.py` but the build still fail. Can someone kindly advice?

**Comment by stephenrauch** [comment]
It looks like the build error was actually due to some glitch in AppVeyor, not because of a code problem. Since this is small change with several submits at this point, you might consider using 'git rebase' to squash the changes into a single commit. If you then push that to github, the test build should run again.

**Comment by kmcheung12** [comment]
Feel free to have a look

**Pull request merged**
