### PR TITLE
Allow usage of custom classes for Row (only subclasses)

### PR DESCRIPTION
**Pull request by gi0baro**
Added `DAL.row_class` parameter to allow usage of custom classes for single rows (only as subclass of `Row`).

Note: I've changed only code that return row objects to user, internally pyDAL still using its `Row` class.

### CODE REVIEW

**Comment by gi0baro** [comment]
@mdipierro @niphlod @ilvalle feedbacks?

**Comment by mdipierro** [comment]
Can we make a db.Row instead of db.row_class() like we do for db.Field and db.Table?

**Comment by gi0baro** [comment]
@mdipierro yep, I will update this PR

**Comment by gi0baro** [comment]
@mdipierro this is ready to be merged.

**Comment by gi0baro** [comment]
@mdipierro Rebased this on master. If everything ok, please merge it.

**Pull request merged**
