### PR TITLE
call after connection just once

### PR DESCRIPTION
**Pull request by michele-comitini**

### CODE REVIEW

**Comment by mdipierro** [comment]
Good catch!

**Comment by gi0baro** [comment]
@mdipierro next time wait for tests to complete, since this broke several adapters.

**Comment by michele-comitini** [comment]
Too fast

**Comment by michele-comitini** [comment]
@mdipierro get the other commit too

**Comment by gi0baro** [comment]
@michele-comitini open another PR from the same branch, I'll merge it.

**Pull request merged**
